services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 5s
      timeout: 5s
      retries: 20

  odoo:
    # Build from our wrapper Dockerfile to avoid image/permission issues
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf:ro
      - ./addons:/mnt/extra-addons
      - ./logs:/var/log/odoo
      - ./filestore:/var/lib/odoo/.local/share/Odoo/filestore
      # If you have Enterprise code, uncomment:
      # - ./enterprise:/mnt/enterprise
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    command: [
      "odoo", "-c", "/etc/odoo/odoo.conf",
      "--dev=reload,qweb,xml"
    ]
    # Important for Codespaces: allow the workspace to mount cleanly
    working_dir: /workspaces/${localWorkspaceFolderBasename}

volumes:
  db-data:
